-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 08:00:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AtosHappyMeter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AtosHappyMeter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AtosHappyMeter` ;
USE `AtosHappyMeter` ;

-- -----------------------------------------------------
-- Table `AtosHappyMeter`.`emotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AtosHappyMeter`.`emotion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `smiley` VARCHAR(6) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Smiley_UNIQUE` (`smiley` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtosHappyMeter`.`emotional_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AtosHappyMeter`.`emotional_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emotion_id` INT NOT NULL,
  `created_date` DATETIME NOT NULL,
  `comment` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_table2_idx` (`emotion_id` ASC),
  CONSTRAINT `fk_table1_table2`
    FOREIGN KEY (`emotion_id`)
    REFERENCES `AtosHappyMeter`.`emotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtosHappyMeter`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AtosHappyMeter`.`administrator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password_hash` CHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `AtosHappyMeter`.`administrator`
-- -----------------------------------------------------
START TRANSACTION;
USE `AtosHappyMeter`;
INSERT INTO `AtosHappyMeter`.`administrator` (`id`, `username`, `password_hash`) VALUES (1, 'admin', '$2a$10$8I3rMrPvn1VmkTV5.4iGi.QDeLpGw1fk.bn9./npHiAdlZE1e87iS');

COMMIT;

